FROM alpine

RUN apk update && apk add wget curl

RUN wget -O test.txt https://github.com/PacktWorkshops/The-Docker-Workshop/blob/master/Chapter03/Exercise3.02/100MB.bin

CMD mkdir -p /var/www/html

WORKDIR /var/www/html

COPY Dockerfile.tar.gz /tmp/
#RUN tar -zxvf /tmp/Dockerfile.tar.gz -C /var/www/html/
#RUN rm /tmp/Dockerfile.tar.gz

ADD Dockerfile.tar.gz /var/www/html/
RUN cat Dockerfile